services:
  orihime:
    build: .
    env_file:
      - .env
    environment:
      PORT: 10000
      PUBLIC_BASE_URL: http://localhost:3000
      WAHA_URL: http://127.0.0.1:3000
      WHATSAPP_API_PORT: 3000
      WHATSAPP_API_HOSTNAME: 127.0.0.1
      WHATSAPP_DEFAULT_ENGINE: GOWS
    ports:
      - "3000:10000"
    volumes:
      - ./data:/orihime/data
      - ./public/assets:/orihime/public/assets
      - ./.sessions:/app/.sessions
      - ./.media:/app/.media
    restart: unless-stopped
